#!/bin/sh

FILE_PATH=$1
NAME=`basename "$FILE_PATH" .js`

cat  << EOF > $FILE_PATH
var h = require('virtual-dom/h');
var state = require('@nichoth/state');

module.exports = $NAME;

function $NAME(opts) {
  var s = state({
    
  });
  
  return s;    
}

$NAME.render = function(state) {
  return h('div', []);
};
EOF
